package main

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"math/big"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/golang-jwt/jwt/v5"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	dynfake "k8s.io/client-go/dynamic/fake"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/rest"
	crclient "sigs.k8s.io/controller-runtime/pkg/client"
	crfake "sigs.k8s.io/controller-runtime/pkg/client/fake"

	kipperv1 "github.com/getkipper/kipper/console-api/api/v1alpha1"
	kipperlabels "github.com/getkipper/kipper/controller/pkg/labels"
)

// updateMatrix rewrites the golden file instead of comparing against it.
var updateMatrix = flag.Bool("update-authz-matrix", false, "rewrite testdata/route_authz_matrix.txt")

const matrixGolden = "testdata/route_authz_matrix.txt"

// The identities the matrix is probed with, in column order. Global role is
// what the kipper-users ConfigMap says; project role is membership of the
// fixture project.
var matrixIdentities = []struct {
	column      string
	email       string // empty sends no token at all
	globalRole  string
	projectRole kipperv1.ProjectMemberRole
}{
	{column: "anon"},
	{column: "outsider", email: "outsider@test.com", globalRole: "deployer"},
	{column: "viewer", email: "viewer@test.com", globalRole: "deployer", projectRole: kipperv1.ProjectRoleViewer},
	{column: "deployer", email: "deployer@test.com", globalRole: "deployer", projectRole: kipperv1.ProjectRoleDeployer},
	{column: "owner", email: "owner@test.com", globalRole: "deployer", projectRole: kipperv1.ProjectRoleOwner},
	{column: "admin", email: "admin@test.com", globalRole: "admin"},
}

// matrixParams fills path parameters with values the fixture knows about, so a
// request reaches its authorization gate rather than stopping at a 404 that
// would hide the gate's answer.
//
// {name} is deliberately the fixture's name in both senses: it is a Project and
// the namespace of that project's default environment. The two meanings take
// different gates, and this matrix is not what distinguishes them — the router
// grouping test is. Here the point is that both kinds of route resolve, so
// every cell reflects an authorization decision.
var matrixParams = map[string]string{
	"name":        matrixProject,
	"namespace":   matrixProject,
	"app":         "shop-api",
	"fn":          "shop-fn",
	"service":     "shop-db",
	"vol":         "shop-data",
	"session":     "session-1",
	"transfer":    "transfer-1",
	"backup":      "backup-1",
	"schedule":    "schedule-1",
	"plan":        "plan-1",
	"key":         "key-1",
	"schema":      "public",
	"table":       "widgets",
	"indexName":   "widgets_pkey",
	"snippetName": "snippet-1",
	"email":       "owner@test.com",
	"username":    "owner",
	"token":       "token-1",
	"id":          "id-1",
	"host":        "shop.example.com",
	"bucket":      "bucket-1",
}

const matrixProject = "shop-prod"

// TestRouteAuthorizationMatrix records what every route in the mux answers to
// every identity, and fails when a cell moves.
//
// It exists for the capability migration: replacing the three-value role rank
// with capability checks touches every gate in console-api, and a silent
// widening or narrowing there is an access change nobody sees. A diff in this
// file is the review.
//
// The statuses themselves are not assertions about what is correct. Several are
// certainly wrong and some are 500s from a handler that a fake client cannot
// satisfy. What matters is that the number does not change for a reason nobody
// intended: a 403 becoming a 200 is the failure this catches.
func TestRouteAuthorizationMatrix(t *testing.T) {
	rows := map[string][]string{}
	var order []string

	for _, id := range matrixIdentities {
		router, token, restore := matrixRouter(t, id.email, id.globalRole, id.projectRole)

		for _, r := range matrixRoutes(t, router) {
			key := r.method + " " + r.pattern
			if _, seen := rows[key]; !seen {
				order = append(order, key)
			}
			rows[key] = append(rows[key], fmt.Sprintf("%s=%d", id.column, matrixProbe(t, router, r, token)))
			// A route that deletes the project or its namespace would
			// otherwise answer for every route after it: the first run of
			// this had an owner deleting the project and then being refused
			// everywhere, which reads as owner holding less than deployer.
			restore()
		}
	}
	sort.Strings(order)

	var b strings.Builder
	b.WriteString("# Generated by TestRouteAuthorizationMatrix. Regenerate with:\n")
	b.WriteString("#   go test ./ -run TestRouteAuthorizationMatrix -update-authz-matrix\n")
	b.WriteString("#\n")
	b.WriteString("# One line per route: the status each identity receives. A cell moving is an\n")
	b.WriteString("# authorization change; review the diff rather than regenerating past it.\n")
	for _, key := range order {
		fmt.Fprintf(&b, "%s\t%s\n", key, strings.Join(rows[key], " "))
	}
	got := b.String()

	if *updateMatrix {
		if err := os.MkdirAll(filepath.Dir(matrixGolden), 0o750); err != nil {
			t.Fatalf("creating testdata: %v", err)
		}
		if err := os.WriteFile(matrixGolden, []byte(got), 0o600); err != nil {
			t.Fatalf("writing the matrix: %v", err)
		}
		t.Logf("wrote %s with %d routes", matrixGolden, len(order))
		return
	}

	want, err := os.ReadFile(matrixGolden)
	if err != nil {
		t.Fatalf("reading the matrix: %v (run with -update-authz-matrix to create it)", err)
	}
	if string(want) == got {
		return
	}
	for _, line := range matrixDiff(strings.Split(string(want), "\n"), strings.Split(got, "\n")) {
		t.Error(line)
	}
}

type matrixRoute struct {
	method    string
	pattern   string
	path      string
	websocket bool
}

// matrixRoutes asks the mux what it serves. Enumerating the source instead
// would describe the routes somebody wrote rather than the ones chi resolves.
func matrixRoutes(t *testing.T, router http.Handler) []matrixRoute {
	t.Helper()
	cr, ok := router.(consoleRouter)
	if !ok {
		t.Fatalf("router is %T, not consoleRouter", router)
	}
	var out []matrixRoute
	err := chi.Walk(cr.api, func(method, pattern string, _ http.Handler, _ ...func(http.Handler) http.Handler) error {
		out = append(out, matrixRoute{method: method, pattern: pattern, path: matrixFill(pattern)})
		return nil
	})
	if err != nil {
		t.Fatalf("walking the router: %v", err)
	}
	if len(out) == 0 {
		t.Fatal("the router serves no routes, so this proves nothing")
	}
	return append(out, matrixWebsocketRoutes...)
}

// matrixWebsocketRoutes are the raw mux's handlers. They bypass the Chi auth
// chain and authenticate and resolve project access themselves, which makes
// them an independent authorization surface rather than a detail of the one
// above: a weakened resolver there widens access with nothing in the Chi table
// to show it.
//
// They are listed rather than walked because http.ServeMux cannot be
// enumerated. That is a maintenance cost, so the count is asserted against the
// registrations in buildRouter.
var matrixWebsocketRoutes = []matrixRoute{
	{method: "GET", pattern: "ws /api/v1/projects/", path: "/api/v1/projects/" + matrixProject + "/apps/shop-api/logs", websocket: true},
	{method: "GET", pattern: "ws /api/v1/terminal/", path: "/api/v1/terminal/" + matrixProject + "/shop-api", websocket: true},
	{method: "GET", pattern: "ws /api/v1/migration/", path: "/api/v1/migration/session-1/progress", websocket: true},
}

// matrixFill turns a chi pattern into a concrete path.
func matrixFill(pattern string) string {
	parts := strings.Split(pattern, "/")
	for i, p := range parts {
		switch {
		case p == "*":
			parts[i] = "wildcard"
		case strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}"):
			name := strings.TrimSuffix(strings.TrimPrefix(p, "{"), "}")
			if v, ok := matrixParams[name]; ok {
				parts[i] = v
				continue
			}
			parts[i] = name
		}
	}
	return strings.Join(parts, "/")
}

// matrixProbe issues one request and returns its status.
//
// The deadline matters: a handler that streams or reaches for the network would
// otherwise hang the suite rather than fail it, and several of these routes do
// one or the other against a fake cluster that cannot answer.
func matrixProbe(t *testing.T, router http.Handler, r matrixRoute, token string) int {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// ProjectScopeQuery reads the namespace from the query string and answers
	// 400 before the role gate when it is absent, so a probe without it records
	// a request-shape failure rather than an authorization decision. Sending it
	// on every route is harmless where it is ignored.
	target := r.path + "?namespace=" + matrixProject
	req := httptest.NewRequest(r.method, target, strings.NewReader("{}")).WithContext(ctx)
	req.Header.Set("Content-Type", "application/json")
	if r.websocket {
		req.Header.Set("Upgrade", "websocket")
		req.Header.Set("Connection", "Upgrade")
		// The raw mux takes the JWT as a WebSocket subprotocol rather than a
		// bearer header, because the browser API can set subprotocols and not
		// headers. Sending the header alone made every identity a 401 and the
		// surface looked probed when it was not.
		if token != "" {
			req.Header.Set("Sec-Websocket-Protocol", "kipper.auth, "+token)
		}
	}
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	rec := httptest.NewRecorder()

	done := make(chan int, 1)
	go func() {
		defer func() {
			// A handler that panics on fixture data it cannot use is still a
			// stable answer for this matrix, and recording it beats failing
			// every run on an unrelated defect.
			if p := recover(); p != nil {
				done <- 599
			}
		}()
		router.ServeHTTP(rec, req)
		done <- rec.Code
	}()

	select {
	case code := <-done:
		return code
	case <-ctx.Done():
		return 598
	}
}

// matrixRouter builds the real router over a fixture the identities can be
// resolved against, and returns a signed token for the caller.
func matrixRouter(t *testing.T, email, globalRole string, projectRole kipperv1.ProjectMemberRole) (http.Handler, string, func()) {
	t.Helper()

	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatalf("generating a signing key: %v", err)
	}
	dex := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]any{"keys": []map[string]string{{
			"kty": "RSA", "kid": "test", "use": "sig", "alg": "RS256",
			"n": base64.RawURLEncoding.EncodeToString(key.N.Bytes()),
			"e": base64.RawURLEncoding.EncodeToString(big.NewInt(int64(key.E)).Bytes()),
		}}})
	}))
	t.Cleanup(dex.Close)

	t.Setenv("DEX_ISSUER", dex.URL)
	t.Setenv("DEX_CLIENT_ID", "kipper-console")
	t.Setenv("CLUSTER_DOMAIN", "example.com")

	users := map[string]string{}
	if email != "" && globalRole != "" {
		users[email] = globalRole
	}
	encoded, err := json.Marshal(users)
	if err != nil {
		t.Fatalf("encoding the user map: %v", err)
	}

	namespace := &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{
		Name:   matrixProject,
		Labels: map[string]string{kipperlabels.Project: matrixProject},
	}}
	clientset := fake.NewClientset(
		&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "kipper-system"}},
		namespace,
		&corev1.ConfigMap{
			ObjectMeta: metav1.ObjectMeta{Name: "kipper-users", Namespace: "kipper-system"},
			Data:       map[string]string{"users": string(encoded)},
		},
	)

	scheme := runtime.NewScheme()
	if err := kipperv1.AddToScheme(scheme); err != nil {
		t.Fatalf("registering the scheme: %v", err)
	}
	project := &kipperv1.Project{
		ObjectMeta: metav1.ObjectMeta{Name: matrixProject},
		Spec:       kipperv1.ProjectSpec{},
	}
	if email != "" && projectRole != "" {
		project.Spec.Members = []kipperv1.ProjectMember{{Email: email, Role: projectRole}}
	}
	crClient := crfake.NewClientBuilder().WithScheme(scheme).WithObjects(project).Build()

	ctx, stopSweepers := context.WithCancel(context.Background())
	t.Cleanup(stopSweepers)
	router := buildRouter(ctx, clientset, dynfake.NewSimpleDynamicClient(scheme),
		&rest.Config{Host: "https://127.0.0.1:6443"}, crClient)

	restore := func() {
		ctx := context.Background()
		if _, err := clientset.CoreV1().Namespaces().Get(ctx, namespace.Name, metav1.GetOptions{}); err != nil {
			fresh := namespace.DeepCopy()
			fresh.ResourceVersion = ""
			if _, cerr := clientset.CoreV1().Namespaces().Create(ctx, fresh, metav1.CreateOptions{}); cerr != nil {
				t.Fatalf("restoring the fixture namespace: %v", cerr)
			}
		}
		var live kipperv1.Project
		if err := crClient.Get(ctx, crclient.ObjectKey{Name: matrixProject}, &live); err == nil {
			live.Spec = *project.Spec.DeepCopy()
			if uerr := crClient.Update(ctx, &live); uerr != nil {
				t.Fatalf("restoring the fixture project: %v", uerr)
			}
		} else {
			fresh := project.DeepCopy()
			fresh.ResourceVersion = ""
			if cerr := crClient.Create(ctx, fresh); cerr != nil {
				t.Fatalf("recreating the fixture project: %v", cerr)
			}
		}
	}

	if email == "" {
		return router, "", restore
	}
	tok := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"iss": dex.URL, "aud": "kipper-console", "sub": email,
		"email": email, "email_verified": true,
		"exp": time.Now().Add(time.Hour).Unix(),
	})
	tok.Header["kid"] = "test"
	signed, err := tok.SignedString(key)
	if err != nil {
		t.Fatalf("signing a token: %v", err)
	}
	return router, signed, restore
}

// matrixDiff reports the lines that differ, so a failure names the routes that
// moved rather than printing two 272-line files.
func matrixDiff(want, got []string) []string {
	index := func(lines []string) map[string]string {
		out := make(map[string]string, len(lines))
		for _, l := range lines {
			if l == "" || strings.HasPrefix(l, "#") {
				continue
			}
			route, statuses, found := strings.Cut(l, "\t")
			if !found {
				continue
			}
			out[route] = statuses
		}
		return out
	}
	a, b := index(want), index(got)

	var out []string
	for route, wantStatuses := range a {
		gotStatuses, present := b[route]
		switch {
		case !present:
			out = append(out, fmt.Sprintf("route gone: %s (was %s)", route, wantStatuses))
		case gotStatuses != wantStatuses:
			out = append(out, fmt.Sprintf("authorization changed: %s\n  was %s\n  now %s", route, wantStatuses, gotStatuses))
		}
	}
	for route, gotStatuses := range b {
		if _, present := a[route]; !present {
			out = append(out, fmt.Sprintf("route added with no recorded authorization: %s (%s)", route, gotStatuses))
		}
	}
	sort.Strings(out)
	return out
}

// TestProjectRolesNest reads the recorded matrix and holds the built-in roles
// to their ordering: viewer's access is a subset of deployer's and deployer's
// of owner's.
//
// It reads the golden file rather than probing again, so it costs nothing and
// says something the matrix alone does not. A matrix diff tells you a cell
// moved; this tells you the move broke the ordering the whole role model rests
// on, which is the failure the capability migration is most likely to produce.
func TestProjectRolesNest(t *testing.T) {
	denied := func(status string) bool { return status == "401" || status == "403" }

	for route, cells := range matrixCells(t) {
		for _, pair := range []struct{ lower, higher string }{
			{"viewer", "deployer"},
			{"deployer", "owner"},
		} {
			low, high := cells[pair.lower], cells[pair.higher]
			if low == "" || high == "" {
				t.Fatalf("%s: the matrix records no %s or %s column", route, pair.lower, pair.higher)
			}
			if !denied(low) && denied(high) {
				t.Errorf("%s admits %s (%s) and refuses %s (%s), so the roles do not nest",
					route, pair.lower, low, pair.higher, high)
			}
		}
	}
}

// matrixCells reads the golden file into route -> column -> status.
func matrixCells(t *testing.T) map[string]map[string]string {
	t.Helper()
	raw, err := os.ReadFile(matrixGolden)
	if err != nil {
		t.Fatalf("reading the matrix: %v", err)
	}
	out := map[string]map[string]string{}
	for _, line := range strings.Split(string(raw), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		route, statuses, found := strings.Cut(line, "\t")
		if !found {
			t.Fatalf("malformed matrix line: %q", line)
		}
		cells := map[string]string{}
		for _, cell := range strings.Fields(statuses) {
			column, status, ok := strings.Cut(cell, "=")
			if !ok {
				t.Fatalf("malformed cell %q on %s", cell, route)
			}
			cells[column] = status
		}
		out[route] = cells
	}
	if len(out) == 0 {
		t.Fatal("the matrix is empty, so this proves nothing")
	}
	return out
}

// TestEveryWebsocketHandlerIsInTheMatrix counts the raw mux's registrations in
// buildRouter and holds matrixWebsocketRoutes to that number.
//
// http.ServeMux cannot be walked, so the rows above are written by hand. That
// is a standing invitation to add a fourth WebSocket handler and forget the
// row, which would leave a whole authorization surface uncovered while every
// test still passed. Reading the source is a poor substitute for walking a
// router and a good one for noticing that a list went stale.
func TestEveryWebsocketHandlerIsInTheMatrix(t *testing.T) {
	source, err := os.ReadFile("main.go")
	if err != nil {
		t.Fatalf("reading main.go: %v", err)
	}
	registered := strings.Count(string(source), "wsMux.HandleFunc(")
	if registered == 0 {
		t.Fatal("found no wsMux registrations, so the count proves nothing")
	}
	if registered != len(matrixWebsocketRoutes) {
		t.Errorf("buildRouter registers %d WebSocket handlers and the matrix lists %d; a surface that bypasses the Chi auth chain is missing its rows",
			registered, len(matrixWebsocketRoutes))
	}
}
