package installer

import (
	"bytes"
	"context"
	"crypto"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"strings"

	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"

	"github.com/getkipper/kipper/controller/pkg/authncfg"
	"github.com/getkipper/kipper/controller/pkg/hopca"
	"github.com/getkipper/kipper/kip/internal/ssh"
)

// Replacing a cluster's certificate authority is a two-sided swap: the API
// server trusts an authority, and Traefik serves a certificate that authority
// signed. Neither side can change at the same instant as the other, so the
// order is forced — widen trust, move the signature, narrow trust — and the
// cluster must never serve a certificate signed by an authority the API server
// does not trust. That state locks every operator out of the OIDC login path.
//
// Kipper does not automate that swap, and this file is what remains after four
// attempts to. The transaction spans the CA Secret, the hop TLS Secret and two
// files on the host: Kubernetes has no cross-object commit and host files take
// no compare-and-swap, so no fence can cover the writes that cause the lockout.
// A process suspended between proving a gate and acting on it will act on a
// cluster that has since moved. The reasoning and the review history are in
// plans/ca-rollover-design.md and plans/ca-rotate-plan.md.
//
// What is left is the part that is sound: reading the material, saying whether
// the two sides agree, and repairing the API server's half. The replacement
// itself is an operator procedure with verification gates, documented in
// docs/en/certificate-authority.md.

const (
	pendingCACertKey = "pending.crt"
	pendingCAKeyKey  = "pending.key" //nolint:gosec // G101: a Secret key name, not a credential
	candidateCertKey = "candidate.crt"
)

// CAPhase is how far a replacement has got, derived from the cluster's own
// material rather than remembered anywhere. Because the replacement is carried
// out by hand, this is what tells an operator returning to a half-finished job
// where they stopped.
type CAPhase string

// The phases of a replacement, in order. Steady is both the start and the end.
const (
	CAPhaseSteady   CAPhase = "steady"
	CAPhaseStaged   CAPhase = "staged"
	CAPhaseExpanded CAPhase = "expanded"
	CAPhasePromoted CAPhase = "promoted"
	CAPhaseNarrowed CAPhase = "narrowed"
)

// ResumePoint names where in the documented procedure this cluster should carry
// on, empty when nothing is in flight. The numbering matches the headings in
// docs/en/certificate-authority.md, so an operator can go straight to the step
// rather than working out which of them already happened.
//
// It reads the leaf as well as the phase because the phase alone cannot tell
// the two halves of a promotion apart: moving the authority and re-signing the
// certificate under it leave the same keys on the CA Secret, and only the
// certificate's own signature says which of them has happened.
func (s CAState) ResumePoint() string {
	switch s.Phase() {
	case CAPhaseStaged:
		return "step 1.4, widening the anchor"
	case CAPhaseExpanded:
		return "step 2.2, promoting the new authority"
	case CAPhasePromoted:
		if s.LeafCert != "" && !hopca.SignedBy([]byte(s.LeafCert), []byte(s.Active)) {
			return "step 2.3, installing the re-signed certificate"
		}
		return "gate 2, confirming the wire before narrowing trust"
	case CAPhaseNarrowed:
		return "gate 3, then step 3.2 to destroy the old authority"
	default:
		return ""
	}
}

// CAState is the material a replacement moves through: the authority and its
// replacement, the certificate they sign, and the anchor the API server
// verifies against.
type CAState struct {
	// Active is the authority currently signing, and ActiveKey signs with it.
	Active, ActiveKey string
	// Pending is an incoming authority that exists but signs nothing yet.
	Pending, PendingKey string
	// Retained is an outgoing authority that still signs the served
	// certificate, or did until moments ago, and must stay trusted.
	Retained string
	// LeafCert and LeafKey are the certificate the cluster serves. The key is
	// never regenerated by a replacement: the gateway pins its public half.
	LeafCert, LeafKey string
	// Candidate is a staged replacement hop key, put there by console-api's key
	// rotation. Replacing the authority underneath one is unsafe, because the
	// candidate carries the signature of whichever authority was active when it
	// was minted.
	Candidate string
	// Anchor is the bundle the API server reads, verbatim.
	Anchor string
	// DexHosts are the issuers the authentication config currently trusts.
	DexHosts []string
	// DomainTransition is the phase of a domain cutover in flight, empty when
	// none is. A cutover rewrites the same authentication config a replacement
	// does, so the two must never overlap.
	DomainTransition string
	// DomainTransitionUnknown records that the cutover could not be checked.
	// It is reported rather than treated as absent: a break-glass command must
	// say which of its checks did not run instead of implying all of them
	// passed.
	DomainTransitionUnknown bool
}

// ReadCAState collects the material behind the certificate authority, reading
// each Secret exactly once so its keys come from one resource version.
//
// This is a report, not a transaction. The two Secrets, the anchor file and the
// authentication config are four reads, and console-api's heartbeat writes one
// of them, so a state that was consistent when it was read can be stale by the
// time it is printed. Nothing here acts on it.
func ReadCAState(client *ssh.Client) (CAState, error) {
	ca, err := readSecretData(client, hopCASecret)
	if err != nil {
		return CAState{}, err
	}
	leaf, err := readSecretData(client, hopCertSecret)
	if err != nil {
		return CAState{}, err
	}
	anchor, err := readHopCA(client)
	if err != nil {
		return CAState{}, err
	}
	hosts, err := readAuthnHosts(client)
	if err != nil {
		return CAState{}, err
	}
	transition, known := readDomainTransition(client)

	return CAState{
		Active:                  ca["tls.crt"],
		ActiveKey:               ca["tls.key"],
		Pending:                 ca[pendingCACertKey],
		PendingKey:              ca[pendingCAKeyKey],
		Retained:                ca[retainedCAKey],
		LeafCert:                leaf["tls.crt"],
		LeafKey:                 leaf["tls.key"],
		Candidate:               leaf[candidateCertKey],
		Anchor:                  anchor,
		DexHosts:                hosts,
		DomainTransition:        transition,
		DomainTransitionUnknown: !known,
	}, nil
}

// readDomainTransition returns the phase of a domain cutover in flight, and
// whether the question could be answered at all.
//
// A failure to ask is reported rather than returned as an error: this feeds a
// command an operator runs when their cluster is already misbehaving, and a
// cluster whose ClusterIdentity cannot be read is exactly when they still need
// to see their certificate state. Losing one check is better than losing the
// whole report, provided the missing check is named.
func readDomainTransition(client *ssh.Client) (phase string, known bool) {
	out, err := client.Run(
		"kubectl get clusteridentities -o jsonpath='{.items[*].status.transition.phase}'")
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(out), true
}

// readSecretData returns every key of a Secret, decoded, from a single read.
// An absent Secret is an empty map rather than an error; a read that fails for
// any other reason is returned, never mistaken for absence.
func readSecretData(client *ssh.Client, name string) (map[string]string, error) {
	out, err := client.Run(fmt.Sprintf(
		"kubectl -n %s get secret %s --ignore-not-found -o jsonpath='{.data}'", hopNamespace, name))
	if err != nil {
		return nil, fmt.Errorf("reading %s/%s: %w", hopNamespace, name, err)
	}
	raw := strings.TrimSpace(out)
	if raw == "" {
		return map[string]string{}, nil
	}
	var encoded map[string]string
	if err := json.Unmarshal([]byte(raw), &encoded); err != nil {
		return nil, fmt.Errorf("reading %s/%s: %w", hopNamespace, name, err)
	}
	data := make(map[string]string, len(encoded))
	for k, v := range encoded {
		decoded, derr := base64.StdEncoding.DecodeString(v)
		if derr != nil {
			return nil, fmt.Errorf("reading %s/%s key %s: %w", hopNamespace, name, k, derr)
		}
		data[k] = string(decoded)
	}
	return data, nil
}

// Phase reports what has been written so far. The distinguishing question at
// each point is whether the anchor mentions the authority in question: an
// authority the API server may not yet trust cannot be allowed to sign, and one
// it may still trust cannot be thrown away.
func (s CAState) Phase() CAPhase {
	switch {
	case s.Pending != "" && s.anchorHas(s.Pending):
		return CAPhaseExpanded
	case s.Pending != "":
		return CAPhaseStaged
	case s.Retained != "" && s.anchorHas(s.Retained):
		return CAPhasePromoted
	case s.Retained != "":
		return CAPhaseNarrowed
	default:
		return CAPhaseSteady
	}
}

func (s CAState) anchorHas(caPEM string) bool {
	return anchorContains(s.Anchor, caPEM)
}

// surplusAnchorAuthorities names authorities the API server is told to trust
// that this cluster does not hold, identified by fingerprint.
//
// Whether the anchor still verifies the served certificate is a different and
// much weaker question, and on its own it is the wrong one. It is satisfied by
// an anchor carrying an extra authority nobody meant to keep — which is the
// state a replacement exists to prevent. An operator who destroys the outgoing
// authority without narrowing the anchor first has thrown away their copy of it
// while the API server goes on accepting logins signed by it, and every other
// check still passes. The last step of a procedure run because a key leaked
// would otherwise report that everything agrees.
func (s CAState) surplusAnchorAuthorities() []string {
	// Without a readable active authority every fingerprint here is "unknown",
	// so every certificate in the anchor looks surplus and the advice becomes
	// "narrow the anchor to the authorities above" — where above is blank, and
	// following it destroys the last copy of the authority. Absent counts as
	// unreadable: an empty tls.crt is what an empty capture in a merge patch
	// leaves behind, which this procedure's own steps warn about.
	if !parsesAsCertificate(s.Active) {
		return nil
	}
	held := map[string]bool{}
	for _, certPEM := range []string{s.Active, s.Pending, s.Retained} {
		if certPEM != "" {
			held[shortFingerprint(certPEM)] = true
		}
	}
	certs, trailing := splitPEMCertificates(s.Anchor)
	seen := map[string]bool{}
	var surplus []string
	for _, certPEM := range certs {
		fingerprint := shortFingerprint(certPEM)
		if seen[fingerprint] {
			continue
		}
		seen[fingerprint] = true
		if !held[fingerprint] {
			surplus = append(surplus, fingerprint)
		}
	}
	if trailing {
		surplus = append(surplus, "unreadable trailing content")
	}
	return surplus
}

// splitPEMCertificates returns each certificate in a bundle separately. The
// anchor is the one place several arrive concatenated, and hopca.ParseCert
// refuses a chain by design.
func splitPEMCertificates(bundlePEM string) (certs []string, trailing bool) {
	rest := []byte(bundlePEM)
	for {
		var block *pem.Block
		block, rest = pem.Decode(rest)
		if block == nil {
			// Anything left that is not whitespace never decoded. Returning the
			// certificates found so far and calling it the whole anchor would
			// let the API server be handed content nothing here has looked at.
			return certs, len(bytes.TrimSpace(rest)) > 0
		}
		if block.Type == "CERTIFICATE" {
			certs = append(certs, string(pem.EncodeToMemory(block)))
		}
	}
}

// trustedAuthorities is every authority that may currently be trusted or may
// currently be signing, which is what the served certificate must chain to for
// the cluster to be in a describable state.
func (s CAState) trustedAuthorities() []byte {
	return hopca.Bundle([]byte(s.Active), hopca.Bundle([]byte(s.Retained), []byte(s.Pending)))
}

// normalisePEM strips whitespace differences so a certificate written into a
// bundle compares equal to the same certificate read out of a Secret.
func normalisePEM(pem string) string {
	return strings.Join(strings.Fields(pem), "")
}

// Anomalies reports material that is malformed rather than merely mid-
// replacement. Every one of these means the cluster needs attention before
// anything else: continuing a replacement from here would either destroy the
// only usable authority or move the public key the gateway pins.
func (s CAState) Anomalies() []string {
	var out []string
	// Unreadable material first: every check below it reads a certificate, and
	// reporting "the key does not match" about bytes that are not a certificate
	// at all sends an operator after the wrong thing.
	for _, m := range []struct{ what, certPEM string }{
		{"the authority", s.Active},
		{"the incoming authority", s.Pending},
		{"the outgoing authority", s.Retained},
		{"the certificate this cluster serves", s.LeafCert},
	} {
		if m.certPEM != "" && !parsesAsCertificate(m.certPEM) {
			out = append(out, fmt.Sprintf("%s is not a readable certificate", m.what))
		}
	}
	for _, fingerprint := range s.surplusAnchorAuthorities() {
		out = append(out, fmt.Sprintf(
			"the API server is anchored on an authority this cluster does not hold (%s); if that is one you replaced, it can still sign logins, narrow the anchor to the authorities above and run 'kip cluster auth sync'",
			fingerprint))
	}
	// A cutover rewrites the same authentication config, so the two operations
	// would each undo the other's work on the anchor.
	switch {
	case s.DomainTransitionUnknown:
		out = append(out, "whether a domain change is in flight could not be checked; a domain change rewrites the same authentication config, so confirm none is running before replacing an authority")
	case s.DomainTransition != "":
		out = append(out, fmt.Sprintf("a domain change is in flight (%s); it rewrites the same authentication config, so let it finish first", s.DomainTransition))
	}
	if s.Active == "" || s.ActiveKey == "" {
		out = append(out, fmt.Sprintf("the authority in %s/%s is missing its certificate or its key", hopNamespace, hopCASecret))
	}
	if s.LeafKey == "" {
		out = append(out, fmt.Sprintf("the hop certificate in %s/%s has no key; generating one would move the public key the gateway pins and take this cluster off the gateway", hopNamespace, hopCertSecret))
	}
	if s.LeafCert == "" {
		out = append(out, fmt.Sprintf("the hop certificate in %s/%s has no certificate", hopNamespace, hopCertSecret))
	}
	if (s.Pending == "") != (s.PendingKey == "") {
		out = append(out, "an incoming authority is half-written: it has a certificate or a key but not both")
	}
	if s.Pending != "" && s.Retained != "" {
		out = append(out, "this cluster holds both an incoming and an outgoing authority, which no single replacement produces")
	}
	if s.Candidate != "" {
		out = append(out, "a replacement hop key is staged; let that rotation finish before replacing the authority, since the two would each re-sign the other's work")
	}
	// The served certificate must chain to something this cluster holds.
	// Pending counts: a stop between promoting the authority and re-signing the
	// leaf is a safe, recoverable boundary, not malformed material.
	if s.Active != "" && s.LeafCert != "" && !hopca.SignedByAny([]byte(s.LeafCert), s.trustedAuthorities()) {
		out = append(out, "the certificate this cluster serves was signed by none of the authorities it holds")
	}
	// A key that does not match its certificate breaks the gateway pin the
	// moment anything re-signs, so it is caught before any mutation. Each is
	// asked only of material that parsed, so an unreadable certificate is
	// reported once, above, rather than again as a mismatch it cannot explain.
	if parsesAsCertificate(s.Active) && s.ActiveKey != "" && !keyMatchesCert(s.Active, s.ActiveKey) {
		out = append(out, "the authority's private key does not match its certificate")
	}
	if parsesAsCertificate(s.LeafCert) && s.LeafKey != "" && !keyMatchesCert(s.LeafCert, s.LeafKey) {
		out = append(out, "the hop certificate's private key does not match its certificate; re-signing would move the public key the gateway pins")
	}
	if parsesAsCertificate(s.Pending) && s.PendingKey != "" {
		if !keyMatchesCert(s.Pending, s.PendingKey) {
			out = append(out, "the incoming authority's private key does not match its certificate")
		}
		if !isCertificateAuthority(s.Pending) {
			out = append(out, "the incoming authority is not a certificate authority")
		}
	}
	if len(s.DexHosts) == 0 {
		out = append(out, "the API server's authentication config names no issuer, so operator login is not configured")
	}
	return out
}

// keyMatchesCert reports whether a private key is the one whose public half the
// certificate carries. The comparison is over the encoded public keys, so it
// holds for any algorithm rather than only the one in use today.
func keyMatchesCert(certPEM, keyPEM string) bool {
	cert, err := hopca.ParseCert([]byte(certPEM))
	if err != nil {
		return false
	}
	block, _ := pem.Decode([]byte(keyPEM))
	if block == nil {
		return false
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return false
	}
	signer, ok := key.(crypto.Signer)
	if !ok {
		return false
	}
	fromCert, err := x509.MarshalPKIXPublicKey(cert.PublicKey)
	if err != nil {
		return false
	}
	fromKey, err := x509.MarshalPKIXPublicKey(signer.Public())
	if err != nil {
		return false
	}
	return bytes.Equal(fromCert, fromKey)
}

func isCertificateAuthority(certPEM string) bool {
	cert, err := hopca.ParseCert([]byte(certPEM))
	return err == nil && cert.IsCA && cert.BasicConstraintsValid
}

// parsesAsCertificate reports whether material is a certificate at all. Empty
// is not: absence is its own anomaly, reported where the material is expected.
func parsesAsCertificate(certPEM string) bool {
	if certPEM == "" {
		return false
	}
	_, err := hopca.ParseCert([]byte(certPEM))
	return err == nil
}

// anchorIsActive reports whether the API server has loaded the authentication
// config that the anchor currently on disk renders to, and whether that could
// be determined at all. This is the distinction between a file being written
// and the running API server having taken it, and it is the check the second
// abandoned design substituted a file read for.
//
// An API server that cannot be reached returns known=false rather than an
// error. This feeds a command an operator runs when the cluster is already
// misbehaving; refusing to report anything because one probe failed would take
// the diagnosis away exactly when it is needed. Reporting it as "not loaded"
// would be worse still, because that is a different fact with a different fix.
func anchorIsActive(client *ssh.Client, state CAState) (loaded, known bool, err error) {
	if len(state.DexHosts) == 0 {
		return false, false, fmt.Errorf("the authentication config names no issuer, so there is nothing to verify")
	}
	loaded, err = authnConfigActive(client, authncfg.Render(state.Anchor, state.DexHosts...))
	switch {
	case errors.Is(err, errMetricsUnreadable):
		return false, false, nil
	case err != nil:
		return false, false, err
	}
	return loaded, true, nil
}

// SyncOperatorAuth re-renders the API server's authentication config from the
// anchor currently on disk, keeping exactly the issuers it already trusts, and
// waits for the API server to report the new config active.
//
// Taking the hosts from the running config rather than from the caller bounds
// what this can do: it can change which authority is trusted but never which
// issuer is, so it cannot silently redirect authentication.
//
// Running it beside another writer of the anchor is still something to avoid.
// It reads that file, verifies the issuers against what it read, and installs a
// config rendered from it; those are three moments, and installing a config
// built from an anchor that has since been replaced puts the API server on an
// authority the cluster no longer serves, which is operator lockout.
//
// The comparison and the write are one remote command, so an anchor that moves
// between them is refused rather than installed. What that cannot cover is the
// interval inside the command itself: a file takes no compare-and-swap. So the
// window is small and the failure is a refusal, but an operator editing the
// anchor by hand at the same moment remains outside anything this can enforce.
func SyncOperatorAuth(client *ssh.Client) error {
	hosts, err := readAuthnHosts(client)
	if err != nil {
		return err
	}
	if len(hosts) == 0 {
		return fmt.Errorf("the authentication config at %s names no issuer; there is nothing to sync", authnConfigPath)
	}
	return EnsureOperatorAuth(client, hosts...)
}

// SyncOperatorAuthIfConfigured re-renders the authentication config when this
// cluster has an issuer to render, and reports whether it did.
//
// This is the shape an unattended caller needs. A cluster with no issuer
// configured has no operator login to repair, so refusing to continue would
// fail an upgrade over the absence of something it was never asked to set up.
// A cluster that does have one must not be told its trust material is in order
// until the API server has actually loaded it.
func SyncOperatorAuthIfConfigured(client *ssh.Client) (synced bool, err error) {
	hosts, err := readAuthnHosts(client)
	if err != nil {
		return false, err
	}
	if len(hosts) == 0 {
		return false, nil
	}
	return true, EnsureOperatorAuth(client, hosts...)
}

// readAuthnHosts returns the issuer hosts the authentication config currently
// trusts, read back from the file the API server is using.
func readAuthnHosts(client *ssh.Client) ([]string, error) {
	out, err := client.Run("cat " + authnConfigPath + " 2>/dev/null || true")
	if err != nil {
		return nil, fmt.Errorf("reading the authentication config: %w", err)
	}
	return parseAuthnHosts(out), nil
}

// parseAuthnHosts extracts issuer hosts from a rendered authentication config.
// The config is generated by authncfg.Render, so the shape is known: one
// "url: https://<host>/dex" line per trusted issuer.
func parseAuthnHosts(config string) []string {
	var hosts []string
	seen := map[string]bool{}
	for _, line := range strings.Split(config, "\n") {
		field := strings.TrimSpace(line)
		if !strings.HasPrefix(field, "url:") {
			continue
		}
		url := strings.TrimSpace(strings.TrimPrefix(field, "url:"))
		url = strings.TrimPrefix(url, "https://")
		host := strings.TrimSuffix(url, "/dex")
		if host == "" || host == url || seen[host] {
			continue
		}
		seen[host] = true
		hosts = append(hosts, host)
	}
	return hosts
}

// ServedByAuthority reports whether the certificate the cluster is currently
// serving verifies against the given authority — asked of the wire, on the
// node, through the same loopback pin the API server uses.
//
// False means the handshake happened and the certificate did not verify. It
// does not narrow that to the signer: an expired certificate or a mismatched
// hostname fails the same way. An error means the question could not be put at
// all, which is a third outcome and never reported as a "no".
//
// This is deliberately not a read of stored material. What Traefik has loaded
// is the only thing that matters when deciding whether an authority can stop
// being trusted, and the two disagree for as long as a reload takes.
func ServedByAuthority(client *ssh.Client, host, caPEM string) (bool, error) {
	if host == "" {
		return false, fmt.Errorf("no issuer host to check")
	}
	// The command answers in words rather than by exiting non-zero, because
	// "the handshake said no" and "the check never ran" are different answers
	// and only one of them is about the authority. Collapsing them reports a
	// cluster as not serving its own active authority whenever the host is
	// briefly unreachable — during a procedure someone is running because a
	// private key leaked, which is the worst moment to be told that wrongly.
	out, err := client.RunStdin(servedByCmd(host), strings.NewReader(caPEM+"\n"))
	if err != nil {
		return false, fmt.Errorf("asking %s which authority signed what it serves: %w", host, err)
	}
	served, answered := servedAnswer(out)
	if !answered {
		return false, fmt.Errorf("asking %s which authority signed what it serves: unexpected answer %q",
			host, strings.TrimSpace(out))
	}
	return served, nil
}

// servedAnswer reads the wire check's reply. answered is false for output that
// says neither thing, which is not the same as a "no" and must not be reported
// as one.
func servedAnswer(out string) (served, answered bool) {
	switch {
	case strings.Contains(out, servedVerified):
		return true, true
	case strings.Contains(out, servedUnverified):
		return false, true
	default:
		return false, false
	}
}

// servedVerified and servedUnverified are what the wire check says back.
//
// curl exits 60 when the certificate it was served does not verify against the
// anchor it was given. That covers more than a different signer — an expired
// certificate and a hostname that does not match both land here — so this
// answers "it did not verify", not "another authority signed it". For deciding
// whether an authority is still needed that is the right question, because a
// certificate that will not verify is not one this authority is holding up.
// Every other exit code means the check never ran.
const (
	servedVerified   = "KIPPER_SERVED_VERIFIED"
	servedUnverified = "KIPPER_SERVED_UNVERIFIED"
)

// servedByCmd builds the handshake that asks the wire which authority signed
// what is being served. The candidate authority arrives on stdin and is written
// to a temporary file, so no certificate reaches the process table, and the
// file is removed however the command exits.
//
// Verification is against that authority alone rather than the system trust
// store: no public authority signed the hop certificate, so a default verifier
// could never accept it and the check would answer "no" for the wrong reason.
func servedByCmd(host string) string {
	return `tmp=$(mktemp) && trap 'rm -f "$tmp"' EXIT && cat > "$tmp" && ` +
		fmt.Sprintf(`{ curl -fsS --cacert "$tmp" --max-time 10 https://%s/dex/.well-known/openid-configuration -o /dev/null && echo %s; } || `+
			`{ rc=$?; [ "$rc" -eq 60 ] && echo %s || exit "$rc"; }`,
			host, servedVerified, servedUnverified)
}

// shortFingerprint names a certificate compactly enough to tell two authorities
// with the same subject apart in a status line, which is exactly the situation
// during a replacement.
func shortFingerprint(certPEM string) string {
	cert, err := hopca.ParseCert([]byte(certPEM))
	if err != nil {
		return "unknown"
	}
	sum := sha256.Sum256(cert.Raw)
	return hex.EncodeToString(sum[:4])
}

// RefuseDuringCAReplacement stops an operation while the cluster's certificate
// authority is part-way through being replaced.
//
// A domain cutover and an authority replacement rewrite the same two files on
// the host, and they disagree about what the trust anchor should hold. The
// cutover's gate renders the anchor it expects from the CA Secret — the active
// signer plus a retained one — while a replacement in progress has an operator
// writing that file by hand, carrying an incoming authority the gate has no
// concept of. The rendered hashes differ, so the gate never matches: the
// cutover parks mid-transaction and tells the operator to resync, which reads
// the same file and produces the same rejected hash.
//
// The certificate status already refuses to start a replacement during a
// cutover. This is that rule in the other direction, which is the one that was
// missing.
func RefuseDuringCAReplacement(ctx context.Context, clientset kubernetes.Interface, client *ssh.Client) error {
	secret, err := clientset.CoreV1().Secrets(hopNamespace).Get(ctx, hopCASecret, metav1.GetOptions{})
	if k8serrors.IsNotFound(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("checking whether a certificate authority replacement is in flight: %w", err)
	}

	if len(secret.Data[pendingCACertKey]) != 0 || len(secret.Data[retainedCAKey]) != 0 {
		return fmt.Errorf(
			"this cluster's certificate authority is part-way through being replaced, and this rewrites the same API server trust config.\n" +
				"    Run 'kip cluster ca status' to see which step is next, finish the replacement, then retry")
	}

	// Those two keys mark a replacement in flight, and the disagreement this
	// exists to prevent outlives them. A replacement finished out of order —
	// the outgoing authority destroyed while the anchor still names it — leaves
	// neither key set and still parks every future cutover, because the gate
	// renders the anchor it expects from the Secret while the file on the host
	// says something else. So ask the question that actually matters: do those
	// two agree right now?
	// A nil *ssh.Client must be tested on the concrete type. Handing it to an
	// interface parameter would produce a non-nil interface holding a nil
	// pointer, and the check inside would not see it.
	if client == nil {
		return nil
	}
	return refuseWhenAnchorDisagreesWithSecret(secret.Data, client)
}

// refuseWhenAnchorDisagreesWithSecret stops an operation whose gate compares an
// anchor rendered from the Secret against the file on the host, when the two do
// not match. Proceeding parks the operation part-way through and names a resync
// that reads the same file and produces the same rejected result.
//
// A host that cannot be reached skips the check rather than failing it. This
// guards against a deadlock; refusing to act because the guard could not run
// would be a worse outcome than the deadlock it prevents.
func refuseWhenAnchorDisagreesWithSecret(caSecret map[string][]byte, client commandRunner) error {
	onHost, err := readHopCA(client)
	if err != nil || onHost == "" {
		//nolint:nilerr // A host that cannot be read skips this guard rather than failing it, per the contract above: refusing to act because the guard could not run is a worse outcome than the deadlock it exists to prevent.
		return nil
	}
	expected := string(hopca.Bundle(caSecret["tls.crt"], caSecret[retainedCAKey]))
	if normalisePEM(onHost) == normalisePEM(expected) {
		return nil
	}
	return fmt.Errorf(
		"the trust anchor on the host does not match the authorities this cluster holds, so the gate that guards this operation cannot pass and it would stop part-way.\n" +
			"    Run 'kip cluster ca status'. If it reports an authority this cluster does not hold, narrowing the anchor to the ones it lists and running 'kip cluster auth sync' clears this")
}
