package handlers

import (
	"context"
	"encoding/json"
	"log"
	"net/http"
	"sort"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/util/retry"

	"github.com/getkipper/kipper/console-api/middleware"
)

const (
	alertsConfigMapName = "kipper-alerts"
	alertsNamespace     = "kipper-system"
	maxAlerts           = 50
	// MaxAlertsPerWrite bounds how many alerts a single write may add, so one
	// mass-crash tick cannot fill the whole cap and evict every earlier alert.
	// Exported so the resource controller can cap a tick's alert/mark pairs to
	// the same bound and keep committed cooldown marks aligned with what the
	// store actually persists.
	MaxAlertsPerWrite = maxAlerts / 2
)

// dismissKey returns a ConfigMap-safe key for tracking a user's dismiss timestamp.
// Email addresses contain @ which is invalid in ConfigMap data keys.
func dismissKey(email string) string {
	safe := strings.NewReplacer("@", "_at_", ".", "_").Replace(email)
	return "dismiss_" + safe
}

// Alert represents a single notification generated by the resource controller.
type Alert struct {
	ID        string `json:"id"`
	Time      string `json:"time"`
	App       string `json:"app"`
	Namespace string `json:"namespace"`
	Action    string `json:"action"`
	Severity  string `json:"severity"`
	Reason    string `json:"reason"`
}

// Alerts provides handlers for the alerting system.
type Alerts struct {
	Client kubernetes.Interface
}

type alertsListResponse struct {
	Alerts []Alert `json:"alerts"`
}

type unreadCountResponse struct {
	Count int `json:"count"`
}

// accessibleAlerts keeps only alerts in projects the caller belongs to.
// Cluster-level alerts (no namespace) resolve to admins only.
func (a *Alerts) accessibleAlerts(r *http.Request, alerts []Alert) []Alert {
	kept := make([]Alert, 0, len(alerts))
	for _, alert := range alerts {
		if canAccessNamespace(r, alert.Namespace) {
			kept = append(kept, alert)
		}
	}
	return kept
}

// List returns the last 50 alerts, newest first.
// GET /api/v1/alerts
func (a *Alerts) List(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()

	alerts := a.accessibleAlerts(r, a.readAlerts(ctx))

	sort.Slice(alerts, func(i, j int) bool {
		return alerts[i].Time > alerts[j].Time
	})

	respondJSON(w, http.StatusOK, alertsListResponse{Alerts: alerts})
}

// UnreadCount returns the number of alerts since the user last dismissed.
// GET /api/v1/alerts/unread-count
func (a *Alerts) UnreadCount(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()

	claims := middleware.UserFromContext(r.Context())
	email := ""
	if claims != nil {
		email = claims.Email
	}

	cm, err := a.Client.CoreV1().ConfigMaps(alertsNamespace).Get(ctx, alertsConfigMapName, metav1.GetOptions{})
	if err != nil {
		respondJSON(w, http.StatusOK, unreadCountResponse{Count: 0})
		return
	}

	dismissTime := cm.Data[dismissKey(email)]

	alerts := a.accessibleAlerts(r, a.readAlerts(ctx))
	count := 0
	for _, alert := range alerts {
		if dismissTime == "" || alert.Time > dismissTime {
			count++
		}
	}

	respondJSON(w, http.StatusOK, unreadCountResponse{Count: count})
}

// Dismiss marks all current alerts as read for the authenticated user.
// POST /api/v1/alerts/dismiss
func (a *Alerts) Dismiss(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()

	claims := middleware.UserFromContext(r.Context())
	email := ""
	if claims != nil {
		email = claims.Email
	}

	cms := a.Client.CoreV1().ConfigMaps(alertsNamespace)
	err := retry.OnError(retry.DefaultRetry, isWriteConflict, func() error {
		cm, getErr := cms.Get(ctx, alertsConfigMapName, metav1.GetOptions{})
		if errors.IsNotFound(getErr) {
			_, createErr := cms.Create(ctx, &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name:      alertsConfigMapName,
					Namespace: alertsNamespace,
					Labels:    map[string]string{"app.kubernetes.io/managed-by": "kipper"},
				},
				Data: map[string]string{dismissKey(email): time.Now().UTC().Format(time.RFC3339)},
			}, metav1.CreateOptions{})
			return createErr
		}
		if getErr != nil {
			return getErr
		}
		if cm.Data == nil {
			cm.Data = make(map[string]string)
		}
		cm.Data[dismissKey(email)] = time.Now().UTC().Format(time.RFC3339)
		_, updateErr := cms.Update(ctx, cm, metav1.UpdateOptions{})
		return updateErr
	})
	if err != nil {
		respondError(w, http.StatusInternalServerError, "failed to update dismiss timestamp")
		return
	}

	respondJSON(w, http.StatusOK, map[string]string{"status": "ok"})
}

func (a *Alerts) readAlerts(ctx context.Context) []Alert {
	cm, err := a.Client.CoreV1().ConfigMaps(alertsNamespace).Get(ctx, alertsConfigMapName, metav1.GetOptions{})
	if err != nil {
		return []Alert{}
	}

	alertsData, ok := cm.Data["alerts"]
	if !ok {
		return []Alert{}
	}

	var alerts []Alert
	if err := json.Unmarshal([]byte(alertsData), &alerts); err != nil {
		return []Alert{}
	}

	return alerts
}

// AddAlert writes a single alert. Thin wrapper over AddAlerts.
func AddAlert(ctx context.Context, client kubernetes.Interface, alert Alert) {
	_ = AddAlerts(ctx, client, []Alert{alert})
}

// AddAlerts appends alerts to the alerts ConfigMap in one conflict-retried
// update and delivers them to Slack off the caller's goroutine. Writing the
// whole batch in a single update avoids a write per alert and keeps the
// update from losing a race with the user-facing Dismiss handler, which
// touches the same ConfigMap. It returns the persist error so a caller that
// tracks alert state (the resource controller's cooldown marks) can hold that
// state back until the write lands and retry on the next tick.
func AddAlerts(ctx context.Context, client kubernetes.Interface, alerts []Alert) error {
	if len(alerts) == 0 {
		return nil
	}

	// Bound how many alerts a single write can add so one mass-crash tick
	// cannot flood the batch and evict all prior history at the total cap.
	// Keeping the newest leaves at least the rest of the cap for history.
	if len(alerts) > MaxAlertsPerWrite {
		log.Printf("alerts: %d alerts in one write exceeds the per-write cap of %d; keeping the newest", len(alerts), MaxAlertsPerWrite)
		alerts = alerts[len(alerts)-MaxAlertsPerWrite:]
	}

	cms := client.CoreV1().ConfigMaps(alertsNamespace)
	err := retry.OnError(retry.DefaultRetry, isWriteConflict, func() error {
		cm, getErr := cms.Get(ctx, alertsConfigMapName, metav1.GetOptions{})
		if errors.IsNotFound(getErr) {
			data, _ := json.Marshal(capAlerts(alerts))
			_, createErr := cms.Create(ctx, &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name:      alertsConfigMapName,
					Namespace: alertsNamespace,
					Labels:    map[string]string{"app.kubernetes.io/managed-by": "kipper"},
				},
				Data: map[string]string{"alerts": string(data)},
			}, metav1.CreateOptions{})
			return createErr
		}
		if getErr != nil {
			return getErr
		}

		var existing []Alert
		if raw, ok := cm.Data["alerts"]; ok {
			_ = json.Unmarshal([]byte(raw), &existing)
		}
		data, _ := json.Marshal(capAlerts(append(existing, alerts...)))
		if cm.Data == nil {
			cm.Data = make(map[string]string)
		}
		cm.Data["alerts"] = string(data)
		_, updateErr := cms.Update(ctx, cm, metav1.UpdateOptions{})
		return updateErr
	})
	if err != nil {
		log.Printf("alerts: failed to persist %d alert(s): %v", len(alerts), err)
		return err
	}

	// Deliver to Slack off the controller loop so a slow or failing webhook
	// never stalls the tick, and detach from the caller's context so an
	// in-flight send survives its cancellation.
	go func() {
		sctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 20*time.Second)
		defer cancel()
		sendSlackBatch(sctx, client, alerts)
	}()
	return nil
}

// isWriteConflict reports whether a ConfigMap write should be retried: an
// optimistic-lock conflict, or an AlreadyExists from a create that raced
// another writer (the retry then reads and updates instead).
func isWriteConflict(err error) bool {
	return errors.IsConflict(err) || errors.IsAlreadyExists(err)
}

func capAlerts(alerts []Alert) []Alert {
	if len(alerts) > maxAlerts {
		return alerts[len(alerts)-maxAlerts:]
	}
	return alerts
}

func sendSlackBatch(ctx context.Context, client kubernetes.Interface, alerts []Alert) {
	webhookURL := getSlackWebhookURL(ctx, client)
	if webhookURL == "" {
		return
	}
	for _, alert := range alerts {
		if err := SendSlackAlert(ctx, webhookURL, alert); err != nil {
			log.Printf("alerts: slack send failed for %s/%s: %v", alert.Namespace, alert.App, err)
		}
	}
}
