package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/stretchr/testify/assert"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
	crclient "sigs.k8s.io/controller-runtime/pkg/client"

	kipperv1 "github.com/getkipper/kipper/console-api/api/v1alpha1"
)

func routeRouter(handler *Apps) *chi.Mux {
	r := chi.NewRouter()
	r.Route("/projects/{name}/apps/{app}", func(r chi.Router) {
		r.Get("/route", handler.GetRoute)
		r.Put("/route", handler.SetRoute)
		r.Delete("/route", handler.DeleteRoute)
	})
	return r
}

func TestGetRoute_NoRouteSet(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	handler := &Apps{Client: fake.NewClientset(), CRClient: testCRClient(app)}

	req := httptest.NewRequest("GET", "/projects/default/apps/web/route", nil)
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.False(t, resp.Enabled)
	assert.Empty(t, resp.Host)
}

func TestGetRoute_WithRoute(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "web.example.com", Path: "/api"},
		},
	}
	handler := &Apps{Client: fake.NewClientset(), CRClient: testCRClient(app)}

	req := httptest.NewRequest("GET", "/projects/default/apps/web/route", nil)
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.True(t, resp.Enabled)
	assert.Equal(t, "web.example.com", resp.Host)
	assert.Equal(t, "/api", resp.Path)
	assert.Equal(t, "https://web.example.com/api", resp.URL)
}

// An App with Spec.Route set but Host empty (created by direct CR apply
// before the API filled it in) still has a real effective host derived
// from CLUSTER_DOMAIN. GetRoute must surface that derived host so the
// Settings tab matches the Routes page.
func TestGetRoute_ImplicitHostDerivedFromDomain(t *testing.T) {
	ns := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "team-test",
			Labels: map[string]string{"kipper.run/environment": "test"},
		},
	}
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "team-test"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			// Host omitted — must be derived from the cluster domain.
			Route: &kipperv1.AppRoute{Path: "/"},
		},
	}
	handler := &Apps{
		Client:   fake.NewClientset(ns),
		CRClient: testCRClient(app),
		Domain:   "kipper.run",
	}

	req := httptest.NewRequest("GET", "/projects/team-test/apps/web/route", nil)
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.True(t, resp.Enabled)
	assert.Equal(t, "web-test.kipper.run", resp.Host)
	assert.Equal(t, "https://web-test.kipper.run/", resp.URL)
}

func TestSetRoute_AutoGeneratedHost(t *testing.T) {
	ns := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "blog-test",
			Labels: map[string]string{"kipper.run/environment": "test"},
		},
	}
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "blog-test"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	handler := &Apps{
		Client:   fake.NewClientset(ns),
		CRClient: testCRClient(app),
		Domain:   "203-0-113-12.kipper.run",
	}

	req := httptest.NewRequest("PUT", "/projects/blog-test/apps/web/route", strings.NewReader(`{}`))
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, "web-test--203-0-113-12.kipper.run", resp.Host)
	assert.True(t, resp.Enabled)
}

func TestSetRoute_ExplicitHost(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	crClient := testCRClient(app)
	handler := &Apps{Client: fake.NewClientset(), CRClient: crClient}

	req := httptest.NewRequest("PUT", "/projects/default/apps/web/route", strings.NewReader(`{"host":"app.example.com","path":"/api"}`))
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, "app.example.com", resp.Host)
	assert.Equal(t, "/api", resp.Path)

	var updated kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated)
	assert.Equal(t, "app.example.com", updated.Spec.Route.Host)
}

func TestSetRoute_RedirectFromRoundTrips(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	crClient := testCRClient(app)
	handler := &Apps{Client: fake.NewClientset(), CRClient: crClient}

	body := `{"host":"example.com","redirect_from":[" www.example.com ","","old.example.net"]}`
	req := httptest.NewRequest("PUT", "/projects/default/apps/web/route", strings.NewReader(body))
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, []string{"www.example.com", "old.example.net"}, resp.RedirectFrom,
		"entries are trimmed and blanks dropped")

	var updated kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated)
	assert.Equal(t, []string{"www.example.com", "old.example.net"}, updated.Spec.Route.RedirectFrom)

	// A follow-up save without the field clears the list, matching the
	// full-state semantics of host and path.
	req = httptest.NewRequest("PUT", "/projects/default/apps/web/route", strings.NewReader(`{"host":"example.com"}`))
	rec = httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)
	assert.Equal(t, http.StatusOK, rec.Code)
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated)
	assert.Empty(t, updated.Spec.Route.RedirectFrom)
}

func TestSetRoute_RedirectFromOverLimitRejected(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	crClient := testCRClient(app)
	handler := &Apps{Client: fake.NewClientset(), CRClient: crClient}

	hosts := make([]string, kipperv1.MaxRedirectFromHosts+1)
	for i := range hosts {
		hosts[i] = fmt.Sprintf("alias-%d.example.com", i)
	}
	body, _ := json.Marshal(map[string]interface{}{"host": "example.com", "redirect_from": hosts})
	req := httptest.NewRequest("PUT", "/projects/default/apps/web/route", strings.NewReader(string(body)))
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusBadRequest, rec.Code)
	assert.Contains(t, rec.Body.String(), "redirect domains")

	var updated kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated)
	assert.Nil(t, updated.Spec.Route, "a rejected request must not partially update the route")
}

func TestSetRoute_AppNotFound(t *testing.T) {
	handler := &Apps{Client: fake.NewClientset(), CRClient: testCRClient()}

	req := httptest.NewRequest("PUT", "/projects/default/apps/nonexistent/route", strings.NewReader(`{"host":"x.com"}`))
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusNotFound, rec.Code)
}

func TestDeleteRoute(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "web.example.com"},
		},
	}
	crClient := testCRClient(app)
	handler := &Apps{Client: fake.NewClientset(), CRClient: crClient}

	req := httptest.NewRequest("DELETE", "/projects/default/apps/web/route", nil)
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)

	var updated kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated)
	assert.Nil(t, updated.Spec.Route)
}

func TestSetRoute_PreservesSecuritySettings(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{
				Host:              "old.example.com",
				NoSecurityHeaders: true,
				CSPAllowlist:      []string{"fonts.googleapis.com"},
			},
		},
	}
	crClient := testCRClient(app)
	handler := &Apps{Client: fake.NewClientset(), CRClient: crClient}

	req := httptest.NewRequest("PUT", "/projects/default/apps/web/route", strings.NewReader(`{"host":"new.example.com"}`))
	rec := httptest.NewRecorder()
	routeRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)

	var updated kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated)
	assert.Equal(t, "new.example.com", updated.Spec.Route.Host)
	assert.True(t, updated.Spec.Route.NoSecurityHeaders)
	assert.Equal(t, []string{"fonts.googleapis.com"}, updated.Spec.Route.CSPAllowlist)
}

func TestGetRouteDNSStatus(t *testing.T) {
	originalLookup := lookupHost
	t.Cleanup(func() { lookupHost = originalLookup })

	clusterIP := "203.0.113.42"
	otherIP := "198.51.100.7"

	node := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-1"},
		Status: corev1.NodeStatus{
			Addresses: []corev1.NodeAddress{
				{Type: corev1.NodeExternalIP, Address: clusterIP},
			},
		},
	}

	tests := []struct {
		name        string
		host        string
		clusterDom  string
		lookupAddrs []string
		lookupErr   error
		wantStatus  string
	}{
		{
			name:        "ok when DNS resolves to cluster IP",
			host:        "example.com",
			clusterDom:  "kipper.run",
			lookupAddrs: []string{clusterIP},
			wantStatus:  dnsStatusOK,
		},
		{
			name:        "mismatch when DNS resolves elsewhere",
			host:        "example.com",
			clusterDom:  "kipper.run",
			lookupAddrs: []string{otherIP},
			wantStatus:  dnsStatusMismatch,
		},
		{
			name:       "unresolved when lookup errors",
			host:       "example.com",
			clusterDom: "kipper.run",
			lookupErr:  fmt.Errorf("no such host"),
			wantStatus: dnsStatusUnresolved,
		},
		{
			name:       "gateway for kipper.run subdomains",
			host:       "myapp-test-203-0-113-42.kipper.run",
			clusterDom: "example.com",
			wantStatus: dnsStatusGateway,
		},
		{
			name:       "wildcard for subdomains of the operator's cluster domain",
			host:       "myapp.example.com",
			clusterDom: "example.com",
			wantStatus: dnsStatusWildcard,
		},
		{
			name:       "kipper.run takes precedence over a kipper.run-based cluster domain",
			host:       "myapp-foo.kipper.run",
			clusterDom: "foo.kipper.run",
			wantStatus: dnsStatusGateway,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			lookupHost = func(string) ([]string, error) { return tt.lookupAddrs, tt.lookupErr }

			app := &kipperv1.App{
				ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
				Spec: kipperv1.AppSpec{
					Image: "nginx", Port: 80, Replicas: int32Ptr(1),
					Route: &kipperv1.AppRoute{Host: tt.host, Path: "/"},
				},
			}
			handler := &Apps{
				Client:   fake.NewClientset(node),
				CRClient: testCRClient(app),
				Domain:   tt.clusterDom,
			}

			r := chi.NewRouter()
			r.Get("/projects/{name}/apps/{app}/route/dns-status", handler.GetRouteDNSStatus)

			req := httptest.NewRequest("GET", "/projects/default/apps/web/route/dns-status", nil)
			rec := httptest.NewRecorder()
			r.ServeHTTP(rec, req)

			assert.Equal(t, http.StatusOK, rec.Code, "body: %s", rec.Body.String())

			var resp dnsStatusResponse
			_ = json.Unmarshal(rec.Body.Bytes(), &resp)
			assert.Equal(t, tt.wantStatus, resp.Status, "message: %s", resp.Message)
			if tt.wantStatus == dnsStatusOK || tt.wantStatus == dnsStatusMismatch || tt.wantStatus == dnsStatusUnresolved {
				assert.Equal(t, []string{clusterIP}, resp.ExpectedIPs)
			}
		})
	}
}

func TestGetRouteDNSStatus_VerifyForcesLookupForWildcard(t *testing.T) {
	originalLookup := lookupHost
	t.Cleanup(func() { lookupHost = originalLookup })
	lookupHost = func(string) ([]string, error) { return []string{"203.0.113.42"}, nil }

	node := &corev1.Node{
		ObjectMeta: metav1.ObjectMeta{Name: "node-1"},
		Status: corev1.NodeStatus{
			Addresses: []corev1.NodeAddress{
				{Type: corev1.NodeExternalIP, Address: "203.0.113.42"},
			},
		},
	}
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "myapp.example.com", Path: "/"},
		},
	}
	handler := &Apps{
		Client:   fake.NewClientset(node),
		CRClient: testCRClient(app),
		Domain:   "example.com",
	}

	r := chi.NewRouter()
	r.Get("/projects/{name}/apps/{app}/route/dns-status", handler.GetRouteDNSStatus)

	req := httptest.NewRequest("GET", "/projects/default/apps/web/route/dns-status?verify=true", nil)
	rec := httptest.NewRecorder()
	r.ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp dnsStatusResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, dnsStatusOK, resp.Status, "verify=true must bypass the wildcard short-circuit")
}

func TestGetRouteDNSStatus_NoRoute(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	handler := &Apps{Client: fake.NewClientset(), CRClient: testCRClient(app)}

	r := chi.NewRouter()
	r.Get("/projects/{name}/apps/{app}/route/dns-status", handler.GetRouteDNSStatus)

	req := httptest.NewRequest("GET", "/projects/default/apps/web/route/dns-status", nil)
	rec := httptest.NewRecorder()
	r.ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp dnsStatusResponse
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, dnsStatusDisabled, resp.Status)
}
