package handlers

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/stretchr/testify/assert"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
	crclient "sigs.k8s.io/controller-runtime/pkg/client"

	kipperv1 "github.com/getkipper/kipper/console-api/api/v1alpha1"
)

func rgRouter(handler *RouteGroups) *chi.Mux {
	r := chi.NewRouter()
	r.Route("/projects/{name}", func(r chi.Router) {
		r.Post("/route-groups", handler.Create)
		r.Put("/route-groups", handler.Update)
		r.Delete("/route-groups/{host}", handler.Delete)
	})
	return r
}

func TestRouteGroups_Create_AutoGeneratedHost(t *testing.T) {
	ns := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "staging",
			Labels: map[string]string{"kipper.run/environment": "staging"},
		},
	}
	frontend := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "frontend", Namespace: "staging"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	api := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "staging"},
		Spec:       kipperv1.AppSpec{Image: "api:v1", Port: 8080, Replicas: int32Ptr(1)},
	}
	crClient := testCRClient(frontend, api)
	handler := &RouteGroups{
		Client:   fake.NewClientset(ns),
		CRClient: crClient,
		Domain:   "203-0-113-12.kipper.run",
	}

	body := `{"mappings":[{"path":"/","app":"frontend"},{"path":"/api","app":"api"}]}`
	req := httptest.NewRequest("POST", "/projects/staging/route-groups", strings.NewReader(body))
	rec := httptest.NewRecorder()
	rgRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeGroupResult
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, "frontend-staging--203-0-113-12.kipper.run", resp.Host)
	assert.Len(t, resp.Mappings, 2)

	var updatedFrontend kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "staging", Name: "frontend"}, &updatedFrontend)
	assert.Equal(t, "frontend-staging--203-0-113-12.kipper.run", updatedFrontend.Spec.Route.Host)
	assert.Equal(t, "/", updatedFrontend.Spec.Route.Path)

	var updatedAPI kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "staging", Name: "api"}, &updatedAPI)
	assert.Equal(t, "frontend-staging--203-0-113-12.kipper.run", updatedAPI.Spec.Route.Host)
	assert.Equal(t, "/api", updatedAPI.Spec.Route.Path)
}

func TestRouteGroups_Create_ExplicitHost(t *testing.T) {
	app := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	handler := &RouteGroups{
		Client:   fake.NewClientset(),
		CRClient: testCRClient(app),
	}

	body := `{"host":"app.example.com","mappings":[{"path":"/","app":"web"}]}`
	req := httptest.NewRequest("POST", "/projects/default/route-groups", strings.NewReader(body))
	rec := httptest.NewRecorder()
	rgRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)
	var resp routeGroupResult
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	assert.Equal(t, "app.example.com", resp.Host)
}

func TestRouteGroups_Create_NormalizesPath(t *testing.T) {
	frontend := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "frontend", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "nginx", Port: 80, Replicas: int32Ptr(1)},
	}
	api := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "api:v1", Port: 8080, Replicas: int32Ptr(1)},
	}
	crClient := testCRClient(frontend, api)
	handler := &RouteGroups{Client: fake.NewClientset(), CRClient: crClient}

	// A stray leading space and a missing leading slash — both easy to type
	// by hand — must be cleaned before they reach the route.
	body := `{"host":"app.example.com","mappings":[{"path":" /","app":"frontend"},{"path":"backend/","app":"api"}]}`
	req := httptest.NewRequest("POST", "/projects/default/route-groups", strings.NewReader(body))
	rec := httptest.NewRecorder()
	rgRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)

	var updatedFrontend kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "frontend"}, &updatedFrontend)
	assert.Equal(t, "/", updatedFrontend.Spec.Route.Path)

	var updatedAPI kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "api"}, &updatedAPI)
	assert.Equal(t, "/backend/", updatedAPI.Spec.Route.Path)

	// The response must echo the normalized paths, not the raw request,
	// so API callers see the canonical state that was actually stored.
	var resp routeGroupResult
	_ = json.Unmarshal(rec.Body.Bytes(), &resp)
	paths := map[string]string{}
	for _, m := range resp.Mappings {
		paths[m.App] = m.Path
	}
	assert.Equal(t, "/", paths["frontend"])
	assert.Equal(t, "/backend/", paths["api"])
}

func TestRouteGroups_Create_EmptyMappings(t *testing.T) {
	handler := &RouteGroups{Client: fake.NewClientset(), CRClient: testCRClient()}

	body := `{"mappings":[]}`
	req := httptest.NewRequest("POST", "/projects/default/route-groups", strings.NewReader(body))
	rec := httptest.NewRecorder()
	rgRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusBadRequest, rec.Code)
}

func TestRouteGroups_Update_AddsAndRemovesMappings(t *testing.T) {
	frontend := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "frontend", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "app.example.com", Path: "/"},
		},
	}
	oldAPI := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "old-api", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "api:v1", Port: 8080, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "app.example.com", Path: "/api"},
		},
	}
	newAPI := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "new-api", Namespace: "default"},
		Spec:       kipperv1.AppSpec{Image: "api:v2", Port: 8080, Replicas: int32Ptr(1)},
	}
	crClient := testCRClient(frontend, oldAPI, newAPI)
	handler := &RouteGroups{Client: fake.NewClientset(), CRClient: crClient}

	body := `{"host":"app.example.com","mappings":[{"path":"/","app":"frontend"},{"path":"/api","app":"new-api"}]}`
	req := httptest.NewRequest("PUT", "/projects/default/route-groups", strings.NewReader(body))
	rec := httptest.NewRecorder()
	rgRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusOK, rec.Code)

	var updatedOld kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "old-api"}, &updatedOld)
	assert.Nil(t, updatedOld.Spec.Route, "old-api route should be cleared")

	var updatedNew kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "new-api"}, &updatedNew)
	assert.Equal(t, "app.example.com", updatedNew.Spec.Route.Host)
	assert.Equal(t, "/api", updatedNew.Spec.Route.Path)
}

func TestRouteGroups_Delete(t *testing.T) {
	app1 := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "web", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "nginx", Port: 80, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "app.example.com", Path: "/"},
		},
	}
	app2 := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "api:v1", Port: 8080, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "app.example.com", Path: "/api"},
		},
	}
	unrelated := &kipperv1.App{
		ObjectMeta: metav1.ObjectMeta{Name: "other", Namespace: "default"},
		Spec: kipperv1.AppSpec{
			Image: "other:v1", Port: 3000, Replicas: int32Ptr(1),
			Route: &kipperv1.AppRoute{Host: "other.example.com", Path: "/"},
		},
	}
	crClient := testCRClient(app1, app2, unrelated)
	handler := &RouteGroups{Client: fake.NewClientset(), CRClient: crClient}

	req := httptest.NewRequest("DELETE", "/projects/default/route-groups/app.example.com", nil)
	rec := httptest.NewRecorder()
	rgRouter(handler).ServeHTTP(rec, req)

	assert.Equal(t, http.StatusNoContent, rec.Code)

	var updated1 kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "web"}, &updated1)
	assert.Nil(t, updated1.Spec.Route)

	var updated2 kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "api"}, &updated2)
	assert.Nil(t, updated2.Spec.Route)

	var updatedOther kipperv1.App
	_ = crClient.Get(context.Background(), crclient.ObjectKey{Namespace: "default", Name: "other"}, &updatedOther)
	assert.Equal(t, "other.example.com", updatedOther.Spec.Route.Host, "unrelated app should be untouched")
}
