#!/usr/bin/env bash
set -euo pipefail

# Regenerates deploy/crds/kustomization.yaml from the CRD files on disk.
# The file is generated, never hand-edited: the crd-drift CI job re-runs
# this script and fails if the committed copy differs, so a CRD added or
# removed from the Go types cannot go missing from the kustomize unit.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
crd_dir="$repo_root/deploy/crds"
out="$crd_dir/kustomization.yaml"

{
  echo "# GENERATED by scripts/generate-crd-kustomization.sh — do not edit."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo ""
  echo "resources:"
  find "$crd_dir" -maxdepth 1 -name '*.yaml' ! -name 'kustomization.yaml' \
    -exec basename {} \; | LC_ALL=C sort | sed 's/^/  - /'
} > "$out"

echo "Wrote $out"
